name = "codecrafters_redis"
version = "1.0.0"

# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = "~> 0.52"
gleam_erlang = "~> 0.31"
gleam_otp = "~> 0.16"
glisten = "~> 7.0"
carpenter = ">= 0.3.1 and < 1.0.0"
birl = ">= 1.8.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
